import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  contenedor: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 16,
  },
  botonIcono: {
    width: 45,
    height: 45,
    backgroundColor: '#FFFFFF',
    borderRadius: 22.5,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 2,
  },
  tituloHeader: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0F172A',
  },
  subtituloNombre: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748B',
    paddingHorizontal: 28,
    marginBottom: 16,
  },
  listaContainer: {
    paddingHorizontal: 24,
    paddingBottom: 100,
  },
  horaTitulo: {
    fontSize: 15,
    fontWeight: '800',
    color: '#334155',
    marginBottom: 12,
  },
  tarjetaMedicamento: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 3,
  },
  tarjetaHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  nombreMedicamento: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0F172A',
    marginBottom: 4,
  },
  dosisMedicamento: {
    fontSize: 14,
    color: '#64748B',
    fontWeight: '500',
  },
  puntoEstado: {
    width: 14,
    height: 14,
    borderRadius: 7,
    marginTop: 4,
  },
  notasContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#F8FAFC',
    padding: 10,
    borderRadius: 10,
    marginTop: 4,
    marginBottom: 12,
    borderLeftWidth: 3,
    borderLeftColor: '#CBD5E1',
  },
  notasTexto: {
    fontSize: 13,
    color: '#475569',
    marginLeft: 8,
    flex: 1,
    fontStyle: 'italic',
    lineHeight: 18,
  },
  estadoRow: {
    flexDirection: 'row',
    marginTop: 4,
  },
  estadoBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 6,
  },
  estadoBadgeTexto: {
    fontSize: 13,
    fontWeight: '700',
  },
});
