import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  contenedor: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 28,
    alignItems: 'center',
  },
  encabezado: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingTop: 55,
    marginBottom: 30,
  },
  botonAtras: {
    width: 40,
    height: 40,
    justifyContent: 'center',
  },
  botonCerrarEncabezado: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  tituloEncabezado: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
  },
  iconoAlerta: {
    width: 72,
    height: 72,
    borderRadius: 36,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  titulo: {
    fontSize: 26,
    fontWeight: '800',
    color: '#0F172A',
    textAlign: 'center',
    marginBottom: 14,
  },
  descripcion: {
    fontSize: 16,
    fontWeight: '400',
    color: '#475569',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 28,
    paddingHorizontal: 12,
  },
  tarjetaEstado: {
    width: '100%',
    backgroundColor: '#F1F5F9',
    borderRadius: 20,
    padding: 18,
    marginBottom: 28,
    minHeight: 180,
    justifyContent: 'flex-end',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  estadoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  estadoPunto: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  estadoTexto: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0F172A',
  },
  ubicacionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
  },
  ubicacionTexto: {
    fontSize: 12,
    fontWeight: '500',
    color: '#64748B',
  },
  textoCerrar: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748B',
  },
  contenedorBotones: {
    width: '100%',
    alignItems: 'center',
    gap: 14,
  },
  botonLlamar: {
    width: '100%',
    height: 56,
    backgroundColor: '#00E676',
    borderRadius: 30,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#00E676',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  botonLlamarTexto: {
    fontSize: 17,
    fontWeight: '700',
    color: '#0F172A',
  },
  botonMensaje: {
    width: '100%',
    height: 56,
    backgroundColor: '#F1F5F9',
    borderRadius: 30,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  botonMensajeTexto: {
    fontSize: 17,
    fontWeight: '700',
    color: '#0F172A',
  },
  textoVerDetalles: {
    fontSize: 15,
    fontWeight: '600',
    color: '#64748B',
    marginTop: 10,
  },
});
