import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  contenedor: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
  },
  botonAtras: {
    padding: 5,
  },
  tituloHeader: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
  },
  encabezado: {
    alignItems: 'center',
    paddingHorizontal: 24,
    marginBottom: 20,
  },
  etiquetaAlerta: {
    backgroundColor: '#FEE2E2',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  etiquetaAlertaTexto: {
    color: '#EF4444',
    fontWeight: '900',
    fontSize: 12,
    letterSpacing: 1,
  },
  mainTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#0F172A',
    textAlign: 'center',
    marginBottom: 4,
  },
  timeText: {
    fontSize: 14,
    color: '#64748B',
    fontWeight: '600',
  },
  mapaContenedor: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  mapa: {
    flex: 1,
    borderRadius: 24,
    overflow: 'hidden',
  },
  panelInferior: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 34 : 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 20,
  },
  indicadorPanel: {
    alignSelf: 'center',
    width: 40,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#E2E8F0',
    marginBottom: 24,
  },
  actionsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  actionButton: {
    flex: 1,
    height: 55,
    borderRadius: 16,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  actionButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F172A',
  },
  mainActionButton: {
    height: 60,
    borderRadius: 30,
    backgroundColor: '#00E676',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
    shadowColor: '#00E676',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  mainActionButtonText: {
    fontSize: 20,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: 0.5,
  },
  resolveButton: {
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  resolveButtonText: {
    fontSize: 14,
    color: '#94A3B8',
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
});