import { StyleSheet } from 'react-native';
import { theme } from '../../../../theme';

export const styles = StyleSheet.create({
  contenedor: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  contenidoScroll: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 50,
    paddingBottom: 40,
  },
  encabezado: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  botonRetroceder: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  tituloEncabezado: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0f172a',
  },
  contenido: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 20,
  },
  iconoCirculo: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#d0fbde',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 28,
  },
  titulo: {
    fontSize: 26,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 12,
    lineHeight: 34,
    textAlign: 'center',
  },
  descripcion: {
    fontSize: 16,
    fontWeight: '400',
    color: '#475569',
    textAlign: 'center',
    marginBottom: 32,
    lineHeight: 24,
    paddingHorizontal: 16,
  },
  contenedorCodigos: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 32,
  },
  cajaCodigo: {
    width: 56,
    height: 76,
    backgroundColor: '#d0fbde',
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textoCodigoCaracter: {
    fontSize: 36,
    fontWeight: '700',
    color: '#0f172a',
  },
  botonCompartir: {
    width: '100%',
    height: 60,
    backgroundColor: theme.colors.primary,
    borderRadius: 40,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
    marginTop: 12,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  textoBotonCompartir: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
  },
  textoError: {
    color: '#DC2626',
    textAlign: 'center',
    marginTop: 32,
    fontSize: 15,
  },
});
