import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    contenedor: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    scrollContenido: {
        paddingHorizontal: 24,
        paddingTop: 60,
        paddingBottom: 100, 
    },
    // Header
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    saludo: {
        fontSize: 12,
        color: '#64748B',
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 4,
    },
    titulo: {
        fontSize: 22,
        fontWeight: '800',
        color: '#0F172A',
    },
    botonNotificacion: {
        width: 45,
        height: 45,
        backgroundColor: '#FFFFFF',
        borderRadius: 22.5,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    // Selector de Fechas 
    fechasContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 35,
    },
    diaItem: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 55,
        height: 75,
        borderRadius: 30,
        backgroundColor: '#FFFFFF',
    },
    diaItemActivo: {
        backgroundColor: '#00E676',
        shadowColor: '#00E676',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 6,
    },
    diaTexto: {
        fontSize: 12,
        color: '#94A3B8',
        fontWeight: '600',
        marginBottom: 4,
    },
    diaTextoActivo: {
        color: '#0F172A',
        fontWeight: '800',
    },
    numeroTexto: {
        fontSize: 16,
        color: '#64748B',
        fontWeight: '700',
    },
    numeroTextoActivo: {
        color: '#0F172A',
        fontWeight: '800',
    },
    // Lista de Medicamentos 
    horaTitulo: {
        fontSize: 15,
        fontWeight: '800',
        color: '#334155',
        marginBottom: 12,
    },
    tarjetaMedicamento: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 20,
        marginBottom: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 3,
    },
    tarjetaHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 8,
    },
    nombreMedicamento: {
        fontSize: 18,
        fontWeight: '800',
        color: '#0F172A',
        marginBottom: 4,
    },
    dosisMedicamento: {
        fontSize: 14,
        color: '#64748B',
        fontWeight: '500',
    },
    // Contenedor de acciones (Editar, Eliminar, Punto)
    accionesContenedor: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    botonAccionMini: {
        backgroundColor: '#DBEAFE',
        padding: 6,
        borderRadius: 8,
        marginRight: 8,
    },
    puntoEstado: {
        width: 14,
        height: 14,
        borderRadius: 7,
    },
    // Sección de Notas Adicionales
    notasContainer: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: '#F8FAFC',
        padding: 10,
        borderRadius: 10,
        marginTop: 4,
        marginBottom: 12,
        borderLeftWidth: 3,
        borderLeftColor: '#CBD5E1',
    },
    notasTexto: {
        fontSize: 13,
        color: '#475569',
        marginLeft: 8,
        flex: 1,
        fontStyle: 'italic',
        lineHeight: 18,
    },
    // Estados y Botones
    estadoPendienteRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 4,
    },
    botonTomarAhora: {
        backgroundColor: '#00E676',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 25,
        flex: 1,
        marginRight: 15,
    },
    textoTomarAhora: {
        color: '#0F172A',
        fontWeight: '800',
        fontSize: 15,
        marginLeft: 8,
    },
    botonPosponer: {
        width: 45,
        height: 45,
        borderRadius: 22.5,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        justifyContent: 'center',
        alignItems: 'center',
    },
    // Botones Flotantes
    fabContainer: {
        position: 'absolute',
        bottom: 20,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        pointerEvents: 'box-none', 
    },
    botonSOS: {
        backgroundColor: '#EF4444',
        width: 65,
        height: 65,
        borderRadius: 32.5,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#EF4444',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 6,
    },
    textoSOS: {
        color: '#FFFFFF',
        fontWeight: '900',
        fontSize: 18,
        marginBottom: -4,
    },
    textoAyuda: {
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: 10,
    },
    botonAgregar: {
        backgroundColor: '#0F172A',
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    }
});